function [] = AnalyzeSubj(subjID)
% Analyzes single subject data
%
% Written by: DJ Strouse
% Last updated: July 22, 2013 by DJ Strouse
%
% INPUTS
% subjID [=] scalar = ID of subject set during quiz administration
%
% OUTPUTS
% none

% init
CalcScores(subjID);
load('data/quiz.mat');
load('data/subjdata.mat');
load('data/subjresults.mat');

% calc ObsPerformance
ObsPopAnsMatchMask(subjID,1:Npair) =...
  ObsPopAns(subjID,:)==PopAns(subjID,PopQOrder(subjID,:));
ObsPopAnsMatch(subjID) = sum(ObsPopAnsMatchMask(subjID,1:Npair))/Npair;
ObsAreaAnsMatchMask(subjID,1:Npair) =...
  ObsAreaAns(subjID,:)==AreaAns(subjID,AreaQOrder(subjID,:));
ObsAreaAnsMatch(subjID) = sum(ObsAreaAnsMatchMask(subjID,1:Npair))/Npair;

% calc ScoresVsConf
minconf = 1;
maxconf = 5;
for n = minconf:maxconf
  % subj conf
  popmask = PopConf(subjID,:)==n;
  PopScoreVsSubjConf(subjID,n) =...
    sum(PopMark(subjID,popmask))/sum(popmask);
  NSubjPopConf(subjID,n) = sum(popmask);
  areamask = AreaConf(subjID,:)==n;
  AreaScoreVsSubjConf(subjID,n) =...
    sum(AreaMark(subjID,areamask))/sum(areamask);
  NSubjAreaConf(subjID,n) = sum(areamask);
  CombScoreVsSubjConf(subjID,n) =...
    (sum(PopMark(subjID,popmask))+sum(AreaMark(subjID,areamask)))...
    /(sum(popmask)+sum(areamask));
  NSubjCombConf(subjID,n) = sum(popmask)+sum(areamask);
  % obs conf
  obspopmask = ObsPopConf(subjID,:)==n;
  PopScoreVsObsConf(subjID,n) =...
    sum(PopMark(subjID,PopQOrder(subjID,obspopmask)))/sum(obspopmask);
  NObsPopConf(subjID,n) = sum(obspopmask);
  obsareamask = ObsAreaConf(subjID,:)==n;
  AreaScoreVsObsConf(subjID,n) =...
    sum(AreaMark(subjID,AreaQOrder(subjID,obsareamask)))/sum(obsareamask);
  NObsAreaConf(subjID,n) = sum(obsareamask);
  CombScoreVsObsConf(subjID,n) =...
    (sum(PopMark(subjID,obspopmask))+sum(AreaMark(subjID,obsareamask)))...
    /(sum(obspopmask)+sum(obsareamask));
  NObsCombConf(subjID,n) = sum(obspopmask)+sum(obsareamask);
end
clear n minconf maxconf popmask areamask obspopmask obsareamask;

% correlations between performance and subj/obs confidence
subjconfs =...
  [PopConf(subjID,PopQOrder(subjID,:)),...
  AreaConf(subjID,AreaQOrder(subjID,:))]';
obsconfs =...
  [ObsPopConf(subjID,:),...
  ObsAreaConf(subjID,:)]';
subjperf =...
  [PopMark(subjID,PopQOrder(subjID,:)),...
  AreaMark(subjID,AreaQOrder(subjID,:))]';
subjdelay =...
  [PopDelay(subjID,PopQOrder(subjID,:)),...
  AreaDelay(subjID,AreaQOrder(subjID,:))]';

[c,p] = corr(subjconfs,obsconfs,'type','Pearson');
SubjVsObsConfPCorr(subjID) = c; clear c;
SubjVsObsConfPCorrPV(subjID) = p; clear p;
[c,p] = corr(subjconfs,obsconfs,'type','Kendall');
SubjVsObsConfKCorr(subjID) = c; clear c;
SubjVsObsConfKCorrPV(subjID) = p; clear p;
[c,p] = corr(subjconfs,obsconfs,'type','Spearman');
SubjVsObsConfSCorr(subjID) = c; clear c;
SubjVsObsConfSCorrPV(subjID) = p; clear p;

[c,p] = corr(subjconfs,subjperf,'type','Pearson');
SubjConfVsScorePCorr(subjID) = c; clear c;
SubjConfVsScorePCorrPV(subjID) = p; clear p;
[c,p] = corr(subjconfs,subjperf,'type','Kendall');
SubjConfVsScoreKCorr(subjID) = c; clear c;
SubjConfVsScoreKCorrPV(subjID) = p; clear p;
[c,p] = corr(subjconfs,subjperf,'type','Spearman');
SubjConfVsScoreSCorr(subjID) = c; clear c;
SubjConfVsScoreSCorrPV(subjID) = p; clear p;

[c,p] = corr(obsconfs,subjperf,'type','Pearson');
ObsConfVsScorePCorr(subjID) = c; clear c;
ObsConfVsScorePCorrPV(subjID) = p; clear p;
[c,p] = corr(obsconfs,subjperf,'type','Kendall');
ObsConfVsScoreKCorr(subjID) = c; clear c;
ObsConfVsScoreKCorrPV(subjID) = p; clear p;
[c,p] = corr(obsconfs,subjperf,'type','Spearman');
ObsConfVsScoreSCorr(subjID) = c; clear c;
ObsConfVsScoreSCorrPV(subjID) = p; clear p;

[c,p] = corr(subjdelay,subjperf,'type','Pearson');
DelayVsScorePCorr(subjID) = c; clear c;
DelayVsScorePCorrPV(subjID) = p; clear p;
[c,p] = corr(subjdelay,subjperf,'type','Kendall');
DelayVsScoreKCorr(subjID) = c; clear c;
DelayVsScoreKCorrPV(subjID) = p; clear p;
[c,p] = corr(subjdelay,subjperf,'type','Spearman');
DelayVsScoreSCorr(subjID) = c; clear c;
DelayVsScoreSCorrPV(subjID) = p; clear p;

[c,p] = corr(subjconfs,subjdelay,'type','Pearson');
SubjConfVsDelayPCorr(subjID) = c; clear c;
SubjConfVsDelayPCorrPV(subjID) = p; clear p;
[c,p] = corr(subjconfs,subjdelay,'type','Kendall');
SubjConfVsDelayKCorr(subjID) = c; clear c;
SubjConfVsDelayKCorrPV(subjID) = p; clear p;
[c,p] = corr(subjconfs,subjdelay,'type','Spearman');
SubjConfVsDelaySCorr(subjID) = c; clear c;
SubjConfVsDelaySCorrPV(subjID) = p; clear p;

[c,p] = corr(obsconfs,subjdelay,'type','Pearson');
ObsConfVsDelayPCorr(subjID) = c; clear c;
ObsConfVsDelayPCorrPV(subjID) = p; clear p;
[c,p] = corr(obsconfs,subjdelay,'type','Kendall');
ObsConfVsDelayKCorr(subjID) = c; clear c;
ObsConfVsDelayKCorrPV(subjID) = p; clear p;
[c,p] = corr(obsconfs,subjdelay,'type','Spearman');
ObsConfVsDelaySCorr(subjID) = c; clear c;
ObsConfVsDelaySCorrPV(subjID) = p; clear p;

% save
clear subjID;
save(...
  'data/subjresults.mat',...
  'ObsPopAnsMatchMask',...
  'ObsAreaAnsMatchMask',...
  'ObsPopAnsMatch',...
  'ObsAreaAnsMatch',...
  'PopScoreVsSubjConf',...
  'AreaScoreVsSubjConf',...
  'NSubjPopConf',...
  'NSubjAreaConf',...
  'PopScoreVsObsConf',...
  'AreaScoreVsObsConf',...
  'NObsPopConf',...
  'NObsAreaConf',...
  'CombScoreVsSubjConf',...
  'CombScoreVsObsConf',...
  'NSubjCombConf',...
  'NObsCombConf',...
  'SubjVsObsConfPCorr',...
  'SubjVsObsConfPCorrPV',...
  'SubjVsObsConfKCorr',...
  'SubjVsObsConfKCorrPV',...
  'SubjVsObsConfSCorr',...
  'SubjVsObsConfSCorrPV',...
  'SubjConfVsScorePCorr',...
  'SubjConfVsScorePCorrPV',...
  'SubjConfVsScoreKCorr',...
  'SubjConfVsScoreKCorrPV',...
  'SubjConfVsScoreSCorr',...
  'SubjConfVsScoreSCorrPV',...
  'ObsConfVsScorePCorr',...
  'ObsConfVsScorePCorrPV',...
  'ObsConfVsScoreKCorr',...
  'ObsConfVsScoreKCorrPV',...
  'ObsConfVsScoreSCorr',...
  'ObsConfVsScoreSCorrPV',...
  'DelayVsScorePCorr',...
  'DelayVsScorePCorrPV',...
  'DelayVsScoreKCorr',...
  'DelayVsScoreKCorrPV',...
  'DelayVsScoreSCorr',...
  'DelayVsScoreSCorrPV',...
  'SubjConfVsDelayPCorr',...
  'SubjConfVsDelayPCorrPV',...
  'SubjConfVsDelayKCorr',...
  'SubjConfVsDelayKCorrPV',...
  'SubjConfVsDelaySCorr',...
  'SubjConfVsDelaySCorrPV',...
  'ObsConfVsDelayPCorr',...
  'ObsConfVsDelayPCorrPV',...
  'ObsConfVsDelayKCorr',...
  'ObsConfVsDelayKCorrPV',...
  'ObsConfVsDelaySCorr',...
  'ObsConfVsDelaySCorrPV',...
  '-append');

end

